module.exports = function (vscode, fs, path, pathdir) {
    var pathfile = path.join(pathdir, ".htaccess");
    fs.access(pathfile, function (err) {
        if (!err) {
            vscode.window.showWarningMessage(".htaccess file already exists!");

        } else {

            fs.open(pathfile, "w+", function (err, fd) {
                if (err) throw err;
                fs.writeFileSync(fd, `# # Generated by Codeigniter 3 Files Creator
                
<IfModule mod_rewrite.c>
    RewriteEngine On

    # # HTTP to HTTPS
    # RewriteCond %{HTTP_HOST} !=localhost
    # RewriteCond %{HTTP_HOST} !=127.0.0.1
    # RewriteCond %{REMOTE_ADDR} !=127.0.0.1
    # RewriteCond %{REMOTE_ADDR} !=::1
    # RewriteCond %{HTTPS} !on
    # RewriteRule ^(.*)$ https://%{HTTP_HOST}/$1 [R=301,L]

    # # Redirect non-www to www
    # RewriteCond %{HTTP_HOST} !=localhost
    # RewriteCond %{HTTP_HOST} !=127.0.0.1
    # RewriteCond %{REMOTE_ADDR} !=127.0.0.1
    # RewriteCond %{REMOTE_ADDR} !=::1
    # RewriteCond %{HTTP_HOST} !^www\.
    # RewriteRule ^(.*)$ http://www.%{HTTP_HOST}/$1 [R=301,L]

    # # Remove WWW from the url
    # RewriteCond %{HTTPS} !=on
    # RewriteCond %{HTTP_HOST} ^www.(.+)$ [NC]
    # RewriteRule ^(.*)$ https://%1/$1 [R=301,L]

    # # Optional to redirect trailing slashes
    # RewriteRule ^(.*)/$ /$1 [L,R=301]

    # Point all URI to codeigniter bootstrap except direct access to file or dir
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.*)$ index.php/$1 [QSA,L]
</IfModule>
            
            
# <IfModule mod_headers.c>
    #   Header set Connection keep-alive
    #   IndexIgnore *
    #   Options -Indexes
    #   <FilesMatch ".(ttf|ttc|otf|eot|woff|woff2|css|js)$">
    #       Header set Access-Control-Allow-Origin "*"
    #   </FilesMatch>

    #   <FilesMatch ".(htaccess)$">
    #       order deny,allow
    #       deny from all
    #       allow from 127.0.0.1
    #   </FilesMatch>

    #   <FilesMatch ".(htpasswd|ini|phps|fla|psd|log|sh|docx|json|sql|rst)$">
    #       order deny,allow
    #       deny from all
    #       allow from 127.0.0.1
    #   </FilesMatch>
# </IfModule>

<IfModule !mod_rewrite.c>
    # If we don't have mod_rewrite installed, all 404's
    # can be sent to index.php, and everything works as normal.
    
    ErrorDocument 404 /index.php
</IfModule>
`);
                fs.close(fd);
            });
            var openPath = vscode.Uri.file(pathfile); //A request file path
            vscode.workspace.openTextDocument(openPath).then(function (val) {
                vscode.window.showTextDocument(val);
            });
            vscode.window.showInformationMessage('Htaccess created successfully! ');
        }
    });
}